STORAGE:
  PATH: data/initiatives/recommendation-engine-v2

RULE:
  PRODUCTS:
    FUNCTION: simulate_products_rule_based
    PARAMS:
      num_products: 100
      seed: 505
  METRICS:
    FUNCTION: simulate_metrics_rule_based
    PARAMS:
      date_start: "2024-01-08"
      date_end: "2024-01-08"
      sale_prob: 0.7
      seed: 505
      granularity: "daily"
